{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dplg",
    "module": "SecureSecrets",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "fwivy5vlijaf3mfbj4wn2bkita"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "SecureSecrets-1.0.0.jar",
          "url": "SecureSecrets-1.0.0.jar",
          "size": 46980,
          "sha512": "d58998d0d677f6b4ef9e05f29a0c1572d5c8aaa10e5008e48c78300a97041dca2b85639d99fea87e4e87765deb89d853563b945a136ac3bc20ce5487b012374e",
          "sha256": "7bb0a7c1fbaaf28423f2fe61dcd5fb0de403335b438b3c33dc64f7417850478b",
          "sha1": "6aa243f5a2f7572d44ec538bcc031769a57bee1c",
          "md5": "a1d3c1bb2db21533716a75a4e653e2f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "SecureSecrets-1.0.0.jar",
          "url": "SecureSecrets-1.0.0.jar",
          "size": 46980,
          "sha512": "d58998d0d677f6b4ef9e05f29a0c1572d5c8aaa10e5008e48c78300a97041dca2b85639d99fea87e4e87765deb89d853563b945a136ac3bc20ce5487b012374e",
          "sha256": "7bb0a7c1fbaaf28423f2fe61dcd5fb0de403335b438b3c33dc64f7417850478b",
          "sha1": "6aa243f5a2f7572d44ec538bcc031769a57bee1c",
          "md5": "a1d3c1bb2db21533716a75a4e653e2f6"
        }
      ]
    }
  ]
}
